FROM registry.redhat.io/web-terminal/web-terminal-tooling-rhel8:1.7

USER 0

# DocumentRoot for Apache
ENV HOME=/home/user
WORKDIR /home/user
RUN curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64 && \
    chmod +x ./kubectl-argo-rollouts-linux-amd64 && \
    mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
