apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "service.name" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "service.name" . }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        {{- include "service.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "service.name" . }}
          image: "b0rr3g0/error-service:0.2"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
          - configMapRef:
              name: "{{ include "service.name" . }}-configmap-env-base"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {}
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause:
          duration: 2m
      trafficRouting:
        istio:
          virtualService:
            name: {{ include "service.name" . }}-vs
            routes:
            - primary
          destinationRule:
            name: {{ include "service.name" . }}-dr
            canarySubsetName: canary
            stableSubsetName: stable 

